### ISSUE TITLE
Errors while selecting a year

### ISSUE THREAD

**Issue by AM-77** [boussadjra/vueye-datepicker#1]
This is the result when clicking the up/down arrows on the year section.

![Screenshot from 2020-07-05 04-53-18](https://user-images.githubusercontent.com/18232579/86524511-cc88e580-be7b-11ea-8cfc-352e7aca18ef.png)

**Comment by boussadjra** [comment]
Thanks for raising the issue, please provide the environment where you ran the example and the full scenario and thanks again

**Comment by AM-77** [comment]
The issue is in the demo.
**Browser:** chromium version 79.0.3945.79 Linux Mint 19.1

**Comment by boussadjra** [comment]
Ok thanks for your contribution i gonna debug the issue

**Comment by boussadjra** [comment]
I tried it out in windows with firefox, edge and chrome and it works, but i don't now why it's showing the `new Date().getTime()` instead of `getFullYear()` , could you please show me the errors generated in console? thanks

**Comment by AM-77** [comment]
There is no error in the console. I m sorry, I think the title mislead you, its a bug not an error.

**Comment by boussadjra** [comment]
Yes it's a bug i have to reproduce it inside  in an environment like yours in order to debug it, since it works in mine. please try it out in another browser like firefox, your contribution is very appreciated

**Comment by AM-77** [comment]
The problem is in `Years.vue` in the `methods` section, somehow (in the first iteration) the `this.year` is a `Date` object, then after the first iteration it became a `Number`, this might fix it.

I tested it also in vivaldi browser (based on chromium), the same issue occurred.

```javascript
next(){
    let _year
    if (typeof this.year === 'number') {
      _year = this.year + 1
    }
    else {
      _year = this.year.getFullYear() + 1
    }
    this.$emit('next-year',_year)
},
prev(){
    let _year
    if (typeof this.year === 'number') {
      _year = this.year - 1
    }
    else {
      _year = this.year.getFullYear() - 1
    }
    this.$emit('prev-year',_year)
}
```
